# Build settings

repository: joelleortiz/joelleortiz.github.io
markdown: kramdown
permalink: pretty

port: 9000

sass:
  style: :nested

remote-theme: jeromelachaud/freelancer-theme

plugins:
  - "jekyll-gist"
  - "jekyll-avatar"
  - "jemoji"
  - "jekyll-mentions"
  - "jekyll-octicons"